apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: inngar
  namespace: dab
  labels:
    team: dab
spec:
  image: {{ image }}
  port: 3000
  replicas:
    min: 1
  resources:
    requests:
      cpu: 50m
  ingresses:
    - https://inngar.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /metrics
  liveness:
    initialDelay: 20
    path: /internal/isAlive
  readiness:
    initialDelay: 20
    path: /internal/isReady
  accessPolicy:
    outbound:
      rules:
        - application: veilarboppfolging
          namespace: poao
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin : true
