apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: inngar
  namespace: dab
  labels:
    team: dab
spec:
  image: {{ image }}
  port: 3000
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 50m
  ingresses:
    - https://inngar.intern.dev.nav.no
    - https://start-arbeidsoppfolging.ansatt.dev.nav.no
  liveness:
    initialDelay: 5
    path: /internal/isAlive
  readiness:
    initialDelay: 5
    path: /internal/isReady
  accessPolicy:
    outbound:
      rules:
        - application: veilarboppfolging
          namespace: poao
        - application: veilarbdialog
          namespace: dab
        - application: veilarbperson
          namespace: obo
        - application: veilarbportefolje
          namespace: obo
        - application: veilarbveileder
          namespace: obo
        - application: veilarbvedtaksstotte
          namespace: obo
        - application: obo-unleash
          namespace: obo
        - application: modiacontextholder
          namespace: personoversikt
      external:
        - host: cdn.nav.no
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
