// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:fnrCode": {
    params: {
      "fnrCode": string;
    };
  };
  "/registrert": {
    params: {};
  };
  "/api/modiacontextholder/*": {
    params: {
      "*": string;
    };
  };
  "/metrics": {
    params: {};
  };
  "/internal/isAlive": {
    params: {};
  };
  "/internal/isReady": {
    params: {};
  };
  "/veilarboppfolging/*": {
    params: {
      "*": string;
    };
  };
  "/veilarbportefolje/*": {
    params: {
      "*": string;
    };
  };
  "/veilarbperson/*": {
    params: {
      "*": string;
    };
  };
  "/veilarbdialog/*": {
    params: {
      "*": string;
    };
  };
  "/veilarbveileder/*": {
    params: {
      "*": string;
    };
  };
  "/veilarbvedtaksstotte/*": {
    params: {
      "*": string;
    };
  };
  "/obo-unleash/*": {
    params: {
      "*": string;
    };
  };
  "/veilarbaktivitet/*": {
    params: {
      "*": string;
    };
  };
  "/mock-settings": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:fnrCode" | "/registrert" | "/api/modiacontextholder/*" | "/metrics" | "/internal/isAlive" | "/internal/isReady" | "/veilarboppfolging/*" | "/veilarbportefolje/*" | "/veilarbperson/*" | "/veilarbdialog/*" | "/veilarbveileder/*" | "/veilarbvedtaksstotte/*" | "/obo-unleash/*" | "/veilarbaktivitet/*" | "/mock-settings" | "/*";
  };
  "routes/ingenBrukerValgtPage.tsx": {
    id: "registrering";
    page: "/";
  };
  "routes/startOppfolgingPaBrukerPage.tsx": {
    id: "registrering-fnr-code";
    page: "/:fnrCode";
  };
  "routes/registrert.tsx": {
    id: "routes/registrert";
    page: "/registrert";
  };
  "routes/dekoratorProxy.tsx": {
    id: "routes/dekoratorProxy";
    page: "/api/modiacontextholder/*";
  };
  "routes/metrics.tsx": {
    id: "routes/metrics";
    page: "/metrics";
  };
  "routes/isAlive.tsx": {
    id: "routes/isAlive";
    page: "/internal/isAlive";
  };
  "routes/isReady.tsx": {
    id: "routes/isReady";
    page: "/internal/isReady";
  };
  "routes/veilarbProxy.tsx": {
    id: "veilarboppfolging";
    page: "/veilarboppfolging/*";
  } | {
    id: "veilarbportefolje";
    page: "/veilarbportefolje/*";
  } | {
    id: "veilarbperson";
    page: "/veilarbperson/*";
  } | {
    id: "veilarbdialog";
    page: "/veilarbdialog/*";
  } | {
    id: "veilarbveileder";
    page: "/veilarbveileder/*";
  } | {
    id: "veilarbvedtaksstotte";
    page: "/veilarbvedtaksstotte/*";
  } | {
    id: "obo-unleash";
    page: "/obo-unleash/*";
  } | {
    id: "veilarbaktivitet";
    page: "/veilarbaktivitet/*";
  };
  "routes/mocksSettings.ts": {
    id: "routes/mocksSettings";
    page: "/mock-settings";
  };
  "routes/redirectToIndex.tsx": {
    id: "routes/redirectToIndex";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "registrering": typeof import("./app/routes/ingenBrukerValgtPage.tsx");
  "registrering-fnr-code": typeof import("./app/routes/startOppfolgingPaBrukerPage.tsx");
  "routes/registrert": typeof import("./app/routes/registrert.tsx");
  "routes/dekoratorProxy": typeof import("./app/routes/dekoratorProxy.tsx");
  "routes/metrics": typeof import("./app/routes/metrics.tsx");
  "routes/isAlive": typeof import("./app/routes/isAlive.tsx");
  "routes/isReady": typeof import("./app/routes/isReady.tsx");
  "veilarboppfolging": typeof import("./app/routes/veilarbProxy.tsx");
  "veilarbportefolje": typeof import("./app/routes/veilarbProxy.tsx");
  "veilarbperson": typeof import("./app/routes/veilarbProxy.tsx");
  "veilarbdialog": typeof import("./app/routes/veilarbProxy.tsx");
  "veilarbveileder": typeof import("./app/routes/veilarbProxy.tsx");
  "veilarbvedtaksstotte": typeof import("./app/routes/veilarbProxy.tsx");
  "obo-unleash": typeof import("./app/routes/veilarbProxy.tsx");
  "veilarbaktivitet": typeof import("./app/routes/veilarbProxy.tsx");
  "routes/mocksSettings": typeof import("./app/routes/mocksSettings.ts");
  "routes/redirectToIndex": typeof import("./app/routes/redirectToIndex.tsx");
};