name: Build and deploy to dev-gcp
run-name: Deploy ${{ github.ref_name }} to dev by ${{ github.actor }}
on:
  workflow_dispatch:

concurrency:
  group: deploy-feature-branch
  cancel-in-progress: true

jobs:
  dev-intern:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      app: inngar-intern
      env: dev
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
    permissions:
      contents: read
      id-token: write

  dev-ekstern:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      app: inngar-ekstern
      env: dev
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
    permissions:
      contents: read
      id-token: write
