name: Build and deploy
on:
  push:
    branches:
      - main

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.app }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        app: [inngar-intern, inngar-ekstern]
    steps:
      - uses: actions/checkout@v6
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies (bun)
        run: bun install --frozen-lockfile
        env:
          BUN_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Build ${{ matrix.app }}
        run: |
          bun run --filter 'common' build
          bun run --filter '${{ matrix.app }}' build
      - name: Remove node_modules and reinstall production dependencies
        run: |
          rm -rf node_modules common/node_modules ${{ matrix.app }}/node_modules
          cd ${{ matrix.app }} && bun install --production
      - name: Build and push image and SBOM to OCI registry
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: dab
          docker_context: ${{ matrix.app }}
          dockerfile: ${{ matrix.app }}/Dockerfile
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      telemetry: ${{ steps.docker-build-push.outputs.telemetry }}

  deploy-dev:
    name: Deploy ${{ matrix.app }} to dev
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        app: [inngar-intern, inngar-ekstern]
    steps:
      - uses: actions/checkout@v6
      - name: Deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/${{ matrix.app }}/dev-gcp.yaml
          VAR: image=${{ needs.build.outputs.image }}
          TELEMETRY: ${{ needs.build.outputs.telemetry }}
          DEPLOY_SERVER: deploy.nav.cloud.nais.io:443

  deploy-prod:
    name: Deploy ${{ matrix.app }} to prod
    needs: [build, deploy-dev]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        app: [inngar-intern, inngar-ekstern]
    steps:
      - uses: actions/checkout@v6
      - name: Deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/${{ matrix.app }}/prod-gcp.yaml
          VAR: image=${{ needs.build.outputs.image }}
          TELEMETRY: ${{ needs.build.outputs.telemetry }}
          DEPLOY_SERVER: deploy.nav.cloud.nais.io:443
