name: Build and deploy
on:
  push:
    branches:
      - main

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  dev-intern:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      app: inngar-intern
      env: dev
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
    permissions:
      contents: read
      id-token: write

  dev-ekstern:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      app: inngar-ekstern
      env: dev
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
    permissions:
      contents: read
      id-token: write

  prod-intern:
    needs: dev-intern
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      app: inngar-intern
      env: prod
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
    permissions:
      contents: read
      id-token: write

  prod-ekstern:
    needs: dev-ekstern
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      app: inngar-ekstern
      env: prod
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
    permissions:
      contents: read
      id-token: write
